---
- name: Install bintray gpg key
  apt_key:
    url: "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"
    state: present

- name: Add grafana repository
  apt_repository:
    repo: "deb https://dl.bintray.com/fg2it/deb jessie main"
    state: present

- name: Install grafana package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - grafana

- name: Set base url for nginx proxy
  lineinfile:
    dest: /etc/grafana/grafana.ini
    regexp: "^;?root_url"
    line: "root_url = %(protocol)s://%(domain)s:/grafana"

- name: Enable and start grafana
  service:
    name: grafana-server
    enabled: yes
    state: started
