# Usage:
# # ansible-playbook -i "air-pi," air-pi.yml
#
# Needs a corresponding .ssh/config entry:
# # Host air-pi
# # 	 Hostname <IP of RPI>
# # 	 User pi
---
- hosts: all
  become: true
  roles:
    - role: rpi
    - role: nginx-proxy
    - role: influxdb
    - role: grafana
    - role: air-pi
    #- role: homeassistant
    #- role: nodered
    #- role: ser2mqtt
    #- role: ble2mqtt
