# Usage:
# # ansible-playbook -i "air-pi," air-pi.yml
#
# Needs a corresponding .ssh/config entry:
# # Host air-pi
# # 	 Hostname <IP of RPI>
# # 	 User pi
---
- hosts: all
  become: true
  vars:
    wlan:
      - ssid: "foobar"
        psk: "d9c76bfe928e3425aac056ad1d4bf3d17d5a67dd72c419b8786e1d7ebb1767b4"
        id_str: "example"
        priority: 0
  roles:
    - role: rpi
    - role: nginx
    - role: homeassistant
    - role: ser2mqtt
    - role: influxdb
    - role: grafana
