- name: Install irssi
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - irssi

- name: Copy irssi config
  synchronize:
    src: "{{ irssi_local }}/"
    dest: "{{ irssi_remote }}"
    mode: push
    recursive: yes
  when: irssi_user != ""
