---
- name: Check if Node-RED is already installed
  stat:
    path: "/usr/bin/node-red-pi"
  register: nodered_bin

- name: Install current node.js and Node-RED
  shell: "yes | bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)"
  args:
    chdir: "/home/{{ rpi_nodered_user }}"
    executable: "/bin/bash"
  become: yes
  become_user: "{{ rpi_nodered_user }}"
  when: nodered_bin.stat.exists == false or rpi_nodered_force_install

- name: Install Node-RED extra nodes
  shell: "npm install {{ item }}"
  args:
    chdir: "/home/{{ rpi_nodered_user }}/.node-red"
    creates: "/home/{{ rpi_nodered_user }}/.node-red/node_modules/{{ item }}"
  become: yes
  become_user: "{{ rpi_nodered_user }}"
  with_items:
    - node-red-node-sqlite
    - node-red-contrib-telegrambot
    - node-red-dashboard

- name: Install Node-RED neopixel
  include: nodered-neopixel.yml
  when: rpi_nodered_neopixel


- name: Enable Node-RED service
  systemd:
    daemon_reload: yes
    name: nodered
    enabled: yes
    state: started
