---
- name: Enable serial uart
  lineinfile:
    dest: /boot/config.txt
    regexp: "^#?enable_uart="
    line: "enable_uart=1"

- name: Disable serial in bootcmd
  replace:
    dest: /boot/cmdline.txt
    regexp: "console=serial0,[0-9]+ "

- name: Disable serial ttyS0 getty
  systemd:
    daemon_reload: yes
    name: serial-getty@ttyS0
    enabled: no
    state: stopped
