---
- name: Copy power-button script
  copy:
    src: power-button.py
    dest: /usr/local/sbin/power-button
    owner: root
    group: staff
    mode: 0744

- name: Copy power-button service
  copy:
    src: power-button.service
    dest: /etc/systemd/system/power-button.service
    owner: root
    group: root
    mode: 0644

- name: Enable power-button service
  systemd:
    daemon_reload: yes
    name: power-button
    enabled: yes
    state: started
