---
- name: Download unicornhat installer
  # Interactive installer must be executed manually if desired
  get_url:
    url: https://get.pimoroni.com/unicornhat
    dest: "{{ nodered_home }}/unicornhat-install.sh"
    mode: 0440

- name: Check if unicornhat is installed
  stat:
    path: "{{ nodered_home }}/Pimoroni/unicornhat/examples/README.md"
  register: nodred_unicornhat_md

- name: Install node-red extra node neopixel
  shell: "npm install {{ item }}"
  args:
    chdir: "{{ nodered_dir }}"
    creates: "{{ nodered_dir }}/node_modules/{{ item }}"
  become: yes
  become_user: "{{ nodered_user }}"
  with_items:
    - node-red-node-pi-neopixel
  when: nodred_unicornhat_md.exists == true
