---
- name: Install prerequisites
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https

- name: Import the node signing key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add nodejs repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update package cache
  apt:
    update_cache: yes
  when: node_repo.changed

- name: Install nodejs
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nodejs

- name: Make nodejs available as node
  command: update-alternatives --install /usr/bin/node nodejs /usr/bin/nodejs 100
  args:
    creates: /usr/bin/node

- name: Install global node packages
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - npm-check-updates
