---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - cmake
    - libjpeg8-dev

- name: Create group
  group:
    name: "{{ mjpg_streamer_user }}"
    state: present
- name: Create user
  user:
    name: "{{ mjpg_streamer_user }}"
    group: "{{ mjpg_streamer_user }}"
    groups:
      - video
    system: yes

- name: Create mjpg-streamer dir
  file:
    path: /opt/mjpg-streamer
    state: directory
    owner: "{{ mjpg_streamer_user }}"
    group: "{{ mjpg_streamer_user }}"
    mode: 0775

- name: Clone mjpg-streamer
  git:
    repo: "https://github.com/jacksonliam/mjpg-streamer.git"
    dest: /opt/mjpg-streamer
    update: no
  register: mjpg_streamer_repo_update
  become: yes
  become_user: "{{ mjpg_streamer_user }}"

- name: Check for mjpg-streamer installation
  stat:
    path: "/usr/local/bin/mjpg_streamer"
  register: mjpg_streamer_bin

- name: Install mjpg-streamer
  block:
    - name: Compile mjpg-streamer
      shell: "cd /opt/mjpg-streamer/mjpg-streamer-experimental && make"
      register: mjpg_streamer_compilelog
      become: yes
      become_user: "{{ mjpg_streamer_user }}"

    - debug: var=mjpg_streamer_compilelog.stdout_lines

    - name: Install mjpg-streamer
      shell: "cd /opt/mjpg-streamer/mjpg-streamer-experimental && make install"
  when: mjpg_streamer_bin.stat.exists == false or mjpg_streamer_force_install

- name: Create web dir
  file:
    path: /var/www/default
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Copy mjpg-streamer html page
  copy:
    src: index.html
    dest: /var/www/default/
    owner: www-data
    group: www-data
    mode: 0644

- name: Create mjpg-streamer service
  template:
    src: mjpg-streamer.service.j2
    dest: /etc/systemd/system/mjpg-streamer.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart mjpg-streamer service

- name: Enable mjpg-streamer service
  systemd:
    daemon_reload: yes
    name: mjpg-streamer
    enabled: yes
  notify:
    - Restart mjpg-streamer service
