---
- name: Install Mosquitto
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - mosquitto
      - mosquitto-clients
  notify: Restart Mosquitto

- name: Copy Mosquitto config
  template:
    src: mosquitto-bind.conf.j2
    dest: /etc/mosquitto/conf.d/bind.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Mosquitto
