---
- name: Set hostname
  include_tasks: hostname.yml
  when: base_hostname | bool

- name: Install packages
  include_tasks: pkg.yml
  when: base_pkg | bool

- name: Add users
  include_tasks: user.yml
  with_items:
    - "{{ base_users | default([]) }}"
  loop_control:
    loop_var: base_user
    label: "{{ base_user.name }}"
  when: (system_type is undefined) or (system_type in (base_user.system_types | default([])))

- name: Disable users
  include_tasks: user-disable.yml
  with_items:
    - "{{ base_users | default([]) }}"
  loop_control:
    loop_var: base_user
    label: "{{ base_user.name }}"
  when: base_user_disable | bool and (system_type is defined) and (system_type not in (base_user.system_types | default([]))) and (not base_user.keep | default(false))

- name: Secure ssh server config
  include_tasks: sshd.yml
  when: base_sshd | bool

- name: Enable unattended upgrades
  include_tasks: upgrade.yml
  when: base_upgrade | bool

- name: Setup time synchronization
  include_tasks: timesync.yml
  when: base_timesync != "none"
