---
- name: Set hostname
  include_tasks: hostname.yml
  when: base_hostname | bool

- name: Install packages
  include_tasks: pkg.yml
  when: base_pkg | bool

- name: Install and secure ssh server config
  include_tasks: sshd.yml
  when: base_sshd | bool

- name: Configure locale
  include_tasks: locale.yml
  when: base_locale | bool

- name: Add users
  include_tasks: user.yml
  with_items:
    - "{{ base_users | default([]) }}"
  loop_control:
    loop_var: base_user
    label: "{{ base_user.name }}"
  # Ignore all disabled users
  # Run for all users when system type is not set
  # Single system type: Run if user has system_type
  # Multiple host system types: Run if the user has one of the system types
  when: >
    not base_user.disabled | default(false) and
    ((system_type is undefined and system_types is undefined) or
    system_type | default("") in (base_user.system_types) or
    system_types | default([]) | intersect(base_user.system_types) | length > 0)

- name: Disable users
  include_tasks: user-disable.yml
  with_items:
    - "{{ base_users | default([]) }}"
  loop_control:
    loop_var: base_user
    label: "{{ base_user.name }}"
  when: >
    base_user_disable | bool and
    base_user.disabled | default(false) or
    (not base_user.keep | default(false) and
    not ((system_type is undefined and system_types is undefined) or
    system_type | default("") in (base_user.system_types) or
    system_types | default([]) | intersect(base_user.system_types) | length > 0))

- name: Setup time synchronization
  include_tasks: timesync.yml
  when: base_timesync != "none"
