---
- name: Set hostname
  include_tasks: hostname.yml
  when: base_hostname | default(false) | bool

- name: Install packages
  include_tasks: pkg.yml

- name: Add users
  include_tasks: user.yml
  with_items:
    - "{{ base_users | default([]) }}"
  loop_control:
    loop_var: base_user

- name: Secure ssh server config
  include_tasks: sshd.yml
  when: base_sshd | default(true) | bool

- name: Enable unattended upgrades
  include_tasks: upgrade.yml
  when: base_upgrade | default(true) | bool

- name: Setup time synchronization
  include_tasks: timesync.yml
  when: base_timesync != "none"
