---
- name: Install packages APT
  include_tasks: pkg-apt.yml
  when: base_pkg | bool and ansible_pkg_mgr == 'apt'

- name: Install packages DNF
  include_tasks: pkg-dnf.yml
  when: base_pkg | bool and ansible_pkg_mgr == 'dnf'

- name: Install minimal packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - vim

- name: Install more packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - acl
      - bash-completion
      - brotli
      - curl
      - git
      - htop
      - jq
      - lm-sensors
      - locales
      - lsof
      - man-db
      - moreutils
      - mosh
      - ncdu
      - passwdqc
      - pwgen
      - python3
      - rdfind
      - rsync
      - smartmontools
      - socat
      - sudo
      - tcpdump
      - telnet
      - tmux
      - unp
      - unzip
      - wget
      - zsh
      - zstd
  when: base_pkg_more | bool
