---
- name: Update package cache and autoremove packages
  apt:
    update_cache: yes
    cache_valid_time: 36000
    autoremove: true
  when: ansible_pkg_mgr == 'apt'

- name: Install aptitude for ansible
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - aptitude
  when: ansible_pkg_mgr == 'apt'

- name: Install selinux for ansible
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libselinux-python
  when: ansible_pkg_mgr == 'dnf'

- name: Install minimal packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - vim

- block:
  - name: Install base packages
    package:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - acl
        - bash-completion
        - brotli
        - curl
        - git
        - htop
        - locales
        - lsof
        - man-db
        - moreutils
        - mosh
        - passwdqc
        - pwgen
        - python3
        - rdfind
        - rsync
        - socat
        - sudo
        - tcpdump
        - telnet
        - tmux
        - unp
        - unzip
        - wget
        - zsh
        - zstd

  - name: Install base packages Debian
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - bind9-host
        - build-essential
        - python3-dev
        - python3-pip
        - python3-setuptools
        - vim-nox
        - picocom
    when: ansible_pkg_mgr == 'apt'

  - name: Install base packages Fedora
    dnf:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - automake
        - gcc
        - gcc-c++
        - kernel-devel
        - make
        - python2-devel
        - python3-devel
        - redhat-rpm-config
        - sqlite
        - vim-enhanced
    when: ansible_pkg_mgr == 'dnf'
  when: base_pkgs|bool

- name: Create locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8
    - de_DE.UTF-8
  when: ansible_pkg_mgr == 'apt'

- name: Set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin
