---
- name: Install unattended-upgrades package
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - unattended-upgrades
      - apt-listchanges
  when: ansible_pkg_mgr == 'apt'
