---
- name: Create group
  group:
    name: "{{ base_user.name }}"
    state: present

- name: Create user
  user:
    name: "{{ base_user.name }}"
    group: "{{ base_user.name }}"
  register: newuser

- name: Set user shell
  user:
    name: "{{ base_user.name }}"
    shell: "/usr/bin/zsh"

- name: Add user groups
  user:
    name: "{{ base_user.name }}"
    append: yes
    groups: "{{ item }}"
  with_items:
    - "{{ base_user.groups | default(base_user_groups) }}"
  when: ansible_pkg_mgr == 'apt'

- name: Update user password when configured
  user:
    name: "{{ base_user.name }}"
    password: "{{ base_user.password }}"
  when: base_user.password is defined

- name: Generate random password for new sudo users
  user:
    name: "{{ base_user.name }}"
    password: "{{ lookup('password', '.cred/{{ inventory_hostname }}/{{ base_user.name }}/pw.txt') | password_hash('sha512') }}"
  when: base_user.password is not defined and newuser.changed and 'sudo' in (base_user.groups | default('sudo'))

- name: Add authorized keys from string
  authorized_key:
    user: "{{ base_user.name }}"
    key: "{{ item }}"
  when: base_user.ssh_keys is defined
  with_items:
    - "{{ base_user.ssh_keys | default([]) }}"

- name: Add authorized keys from github
  authorized_key:
    user: "{{ base_user.name }}"
    key: "https://github.com/{{ item }}.keys"
  ignore_errors: yes
  when: base_user.ssh_keys_gh is defined
  with_items:
    - "{{ base_user.ssh_keys_gh | default([]) }}"

- name: Add authorized keys from gitlab
  authorized_key:
    user: "{{ base_user.name }}"
    key: "https://{{ item }}.keys"
  ignore_errors: yes
  when: base_user.ssh_keys_gitlab is defined
  with_items:
    - "{{ base_user.ssh_keys_gitlab | default([]) }}"

- name: Add authorized keys from folder
  authorized_key:
    user: "{{ base_user.name }}"
    key: "{{ lookup('file', item) }}"
  when: base_user.ssh_keys_path is defined
  with_fileglob:
    - "{{ base_user.ssh_keys_path }}/*"

- name: Add personal configuration
  include_tasks: dotfiles.yml
  when: base_user.dotfiles_url is defined
